### ISSUE TITLE
COMMON  logout operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#10]
Requirement a) of section 3.3.9.2 states :
a) Upon reception of the message the operation shall remove the matched user from the set of logged in users.

Is the "user" removed from the archive or from the provider ?

**Comment by SamCooper** [comment]
Done.

**Comment by BEHAL** [comment]
I do not understand your answer to my question. What do you mean by "done" ?

**Comment by SamCooper** [comment]
I've clarified the text to state what happens with the archive. they are removed from the provider but not the archive.
