### ISSUE TITLE
services supported by the provider

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#104]
assertion 3.4.13.2.f for the operation storeCurrent has been added. It says:
If the serviceKey field is not NULL and the referenced service is not supported by the service provider an UNKNOWN error shall be returned.
The Configuration service has no means to know what are the services supported by a provider. So if I want to check this assertion, then I will check that a ServiceConfiguration has already been declared for that service and provider. This prevents a use case where we would like to declare a single service configuration with storeCurrent (which could be the case for declaring a non COM compliant configuration).

**Comment by SamCooper** [comment]
ok
