### ISSUE TITLE
Figure C-4

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#107]
This figure displays the sequence diagram of the storeCurrent operation. It must be updated with the new IP of the operation.

**Comment by SamCooper** [comment]
I need to make this update in the diagrams

**Comment by SamCooper** [comment]
What changes need to be made to this diagram?

**Comment by lacourte** [comment]
The diagram displays the storeCurrent operation as a REQUEST IP. It is actually an INVOKE IP. It misses the RESPONSE message.

**Comment by SamCooper** [comment]
Done
