### ISSUE TITLE
COMMON Handover operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#11]
It is said in section 3.3.11.2 that :
l) The source link of the new LoginInstance COM object shall be set to NULL.
m) The provider should update in the COM archive the LoginInstance COM object that represents the previous login by setting its source link to the object instance identifier of the new LoginInstance COM object.

To me, it is the old loginInstance object that is the source of the new loginInstanceobject because it is the user in his previous role who decided to change. Why do you consider that the "new " loginInstance object is the source of the old one ? What use case do you have in mind ?

**Comment by SamCooper** [comment]
Logically you are right, in that it makes more sense that way around. My thinking though was that it should be easier to tell who was still logged in when using the COM Archive operations.

But thinking about it I am not so sure it would actually be useful like it is currently defined.

**Comment by SamCooper** [comment]
I've changed the model to your suggestion.
