### ISSUE TITLE
[Configuration service] What should the source of the config switched event be if the body indicates failure to switch configs?

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#113]
The ConfigurationSwitched event emitted as a result of the Activate operation has a boolean body indicating success or failure, the source relation is defined in the spec as referencing the last activated configuration.

Normal successful execution should link to the last activated configuration in the source of the config switched event, if it fails to switch do we set this instead to the current config (as we never switched) or to null?

**Comment by lacourte** [comment]
As it is not defined in the spec, I assume any value is valid.
I do not check this in the tests.

**Comment by apinder** [comment]
I've updated this to be NULL in the spec
