### ISSUE TITLE
[Configuration service] Should we emit a ConfigurationSwitched event when we initially configure the configured service using getCurrent?

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#114]
3.4.9.1 states:

> "The [getCurrent] operation can also be used to determine the initial configuration of a service provider before it has been activated, it is therefore a useful operation to call by a service provider during start-up to determine its initial configuration."

The configured prototype initialises itself with the getCurrent operation - as above - in terms of the Configured service this is a switch of configuration but it is not triggered by an activate interaction - should we emit a ConfigurationSwitched event in this case or not?

This might be out of scope and implementation specific so feel free to ignore.

**Comment by lacourte** [comment]
I would say no, but it seems it is not explicitely forbidden so it should be possible.
I hope my tests will handle that properly if you do.

**Comment by apinder** [comment]
Agree, clarified in the spec that we should not emit a switched event if this is the case
