### ISSUE TITLE
[Configuration service] Should the Remove operation also allow removal of service level configurations?

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#115]
3.4.12.1 states : 

> "The remove operation, removes a provider configuration from the list of configurations available for that provider in the configuration service." 

Yet further down it states

> "e) If any of the supplied configuration objects are not provider or service configuration objects then an INVALID error shall be returned." 

It should either be Provider and Service configs for both statements or just Provider configs for both statements.

It also only mentions provider configurations in requirement c):

> "The second argument shall contain a list of provider configurations to remove from the list of configurations available for the specific service provider."

For the prototype I've allowed both Provider and Service configs as otherwise they'd be no way of removing Service level configurations individually.

**Comment by lacourte** [comment]
I understand "provider configuration" here as a configuration of the service provider. The configuration may then be either a ProviderConfiguration or a ServiceConfiguration.
However "provider configuration" is also used elsewhere in the document for ProviderConfiguration. So there may be a risk of confusion here.

**Comment by apinder** [comment]
Closing as this is now clarified
