### ISSUE TITLE
[Configuration service] Assuming UTF-8 encoding for the XML export

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#116]
Currently using UTF-8 encoding for the XML export, this might be worth making explicit though or it might be covered already by more generalised specs in which case ignore

**Comment by lacourte** [comment]
I agree with UTF-8 encoding. This may be considered an out-of-band agreement, not required in the spec ?

**Comment by apinder** [comment]
Agreed, closing
