### ISSUE TITLE
[Configuration service] What should the identifier of the returned File object be when exporting XML?

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#117]
For the prototype this is configExport_{confObjId}.xml but this is not specified anywhere in the spec.

**Comment by lacourte** [comment]
It could be defined as an out-of-band agreement.
For our tests, it is probably simpler to agree that we fill in the content field of the File structure.

**Comment by apinder** [comment]
Agreed, closing
