### ISSUE TITLE
[Configuration service] List operation when supplied with a ServiceKey filter does not specify whether it's a logical AND or logical OR

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#118]
3.4.8.2 d) states:

> If the request configuration type is SERVICE, then an optional filter may be supplied in the serviceKey field where the ServiceKey composite holds the service area, service, and version values to match on

Should we match only when all of these attributes of the service key match or should we OR them?

The prototype has been implemented with an AND.

**Comment by lacourte** [comment]
Same from my side.

**Comment by apinder** [comment]
Updated spec to go with logical AND
