### ISSUE TITLE
COMMON Interact service : listActiveInteractions

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#12]
Can you explain why the listActiveInteractions is supported in Replay Mode whereas all the other operations cannot be used in this mode ? 
What result will the user obtain ? The list of the interaction requests that were used during the "source" session of the replay session (live or simulated) ?
Will this list enable him to get the responses provided to the requests ?

Can you indicate what use case you have in mind ?

**Comment by SamCooper** [comment]
Only read-only operations can be supported in replays because you cannot modify a historic replay. So, the listActiveInteractions operation is read only therefore it would return to you the interactions that were active at that time in the replay.

**Comment by SamCooper** [comment]
Closed
