### ISSUE TITLE
Configuration test service

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#120]
This is not an issue, but an explanation of what is expected from the ConfigurationTest service.

The Configuration service involves interactions with configured services. In order to perform the tests we need an implementation of such a configured service. This implementation behaves as a standard MAL service, but it also provides a direct interface used by the fitnesse tests.

The MAL interface is defined in the CommonPrototype.xml file. It actually defines 3 services: ConfigurationTest, ConfigurationTestNC and ConfigurationTestHC. Those services intend to implement respectively the COM compliant, non-COM compliant, and hard-coded configuration behaviors of the standard.

A single service provider is deployed to serve the 3 services. It is created by the configurationTestService function of the class LocalMALInstance. The function is called by fitnesse. The service provider thus runs in the client part of the testbed. The service provider is created by loading the class org.ccsds.moims.mo.common.test.configuration.ConfigurationTest which is provided in a separate artefact. Both CNES and ESA provide an implementation of the class. The proper artefact is selected through maven profiles.

The ConfigurationTest class implements the ConfigurationTestInterface interface. This interface allows the fitnesse tests to interact directly with the test services. The general requirements for this interface are described in the file. Please ask if some are unclear.

**Comment by SamCooper** [comment]
Not a RID, just test description.

Closing
