### ISSUE TITLE
[Directory service] Lookup return value

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#121]
Two statements are inconsistent:
3.2.7.1: If no match is found, then an empty list is returned.
3.2.7.2.p: If no service providers match the supplied filter then NULL shall be returned.

**Comment by apinder** [comment]
Agree, my implementation was to go with:

> 3.2.7.2.p: If no service providers match the supplied filter then NULL shall be returned.

Will change if necessary.

Not sure if you got the email - as I don't think it's your primary email but just thought I'd let you know that the implementation on our side should be done now taking into account the ambiguities and using the configuration service pattern you've used. Let us know if you find any problems/ambiguities and if there's anything we can help with.

**Comment by apinder** [comment]
I've updated the spec to conform to an empty list (rather than return null)

**Comment by SamCooper** [comment]
Closed
