### ISSUE TITLE
[Directory service] assertion 3.2.8.2.j

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#122]
> The created objects should be stored in the COM archive by the service provider.
The "service provider" here is ambiguous. I cannot believe it represents the "service to be added or updated in the directory service", but it would be good to specify it is the "directory service provider".

**Comment by apinder** [comment]
Updated the spec to clarify which service provider.

**Comment by SamCooper** [comment]
Closed
