### ISSUE TITLE
[Directory Service] ProviderAddressDetails

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#123]
Assertion 3.2.8.2.F says

> For each contained ProviderAddressDetails structure if the supportedLevels list is empty or the priorityLevels field is '0' then an INVALID error shall be returned.

The structure type is actually AddressDetails. Such structures may be found in two fields of the publishProvider parameter.

1. as the providerAddresses field of the ProviderDetails structure
2. as the serviceAddresses field of the inner ServiceCapability structures

I had first interpreted ProviderAddressDetails as the first occurrence. However the test suite actually tests the second occurrence, and not the first.
I assume now that all the occurrences should be concerned by the assertion. I suggest it to be clarified.

**Comment by apinder** [comment]
The `ProviderDetails` type (4.2.1) describes the AddressDetails field:

> List of addresses for all services of this service provider unless service specific addresses are supplied in the serviceCapabilities field. 

This sounds like we should be checking for both of them. I've updated the spec accordingly.

**Comment by SamCooper** [comment]
Closed
