### ISSUE TITLE
COMMON Interact service : acknowledgement field of the interact request operations

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#15]
For all the interact request operations, it is said that :
    " The acknowledgement objInstId field shall hold the COM object instance identifier of the InteractRequest COM object"

If my understanding is correct, the information needed by the display application is held by the actual Interact request object, not by the generic one. To get this information, the display application will have to retrieve firstly the generic InteractRequest object in order to obtain the object instance Id of the actual interact request object and then perform a 2nd retrieval of this object.

Why not directly use the objInstId of the actual Interact Request object, that is to say the InteractConfirmRequest object, the InteractChoiceRequest object or the InteractValueRequest object ?

**Comment by SamCooper** [comment]
I shall change the operations to return both sets of information in the ack.
