### ISSUE TITLE
COMMENT Interact service : terminomogy consistency

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#16]
The 3 following requirements appear for each type of Interact Request Operation :
h) The acknowledgement objInstId field shall hold the COM object instance identifier of the InteractRequest COM object.
i) The returned COM object instance identifier shall be used by the matching respond operation to match this interaction.
j) The returned COM object instance identifier may be used by the cancelInteraction operation to cancel this interaction.

1) Can you confirm that "the acknowledgement objInstId field " mentionned in statement h) is also "the returned COM object instance identifier " mentionned in statements i) & j)
2) if these 2 terms refer to the same object, could you please consistently use only one of these terms  ?

**Comment by SamCooper** [comment]
Done.
