### ISSUE TITLE
COMMON Interact : meaning of "UNKNOWN" error

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#18]
Sections 3.4.7.3.1, 3.4.9.3.1, 3.4.11.3.1 and 3.4.13.3.2 state :
   "User could not be found to satisfy interaction"
This error code is also generated when the role provided by the consumer cannot be found. Therefore, the message should be completed and say :
   "User or role could not be found to satisfy interaction"

**Comment by SamCooper** [comment]
Done
