### ISSUE TITLE
COMMON Interact : Authentication Identifier of a role

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#19]
Requirement c) of sections 3.4.8.2, 3.4.10.2, 3.4.12.2 & 3.4.14.2 says :
c) If the authentication identifier of the SUBMIT message does not correspond to the correct user or role for the interaction then an AUTHENTICATION_FAIL error shall be returned.

The login operation returns an authentication identifier for a profile [username, role] and not for a role only, which implies that a role can be associated to multiple authentication ids (as many as the number of users logged with the considered role). 

Therefore, should it not be more accurate and clearer to say :
    "If the authentication identifier of the SUBMIT message does not correspond to a profile whose username or role is the requested user or role for the interaction then an AUTHENTICATION_FAIL error shall be returned" ?

**Comment by SamCooper** [comment]
Done.
