### ISSUE TITLE
COMMON Interact : Time out management

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#20]
For each Interaction Request operation, on the "consumer side", it is said in sections 3.4.7.2, 3.4.9.2, 3.4.11.2 & 3.4.13.2 : 
k) If responseTimeout field of the interactionDetails field contains a non-zero duration and no response has been received in that time then the interaction shall be considered timed out.
l) If the interaction has timed out then the provider shall create new InteractResult and InteractTimedoutResult COM objects.
m) If the interaction has timed out then the created timed out objects should be stored in the COM archive by the service provider.
n) If the interaction has timed out then an InteractComplete COM event shall be created and distributed by the service provider.
o) If the interaction has timed out then a TIMEDOUT error shall be returned

Whereas, on the "response" side it is said in sections 3.4.8.2, 3.4.10.2, 3.4.12.2 & 3.4.14.2 :
g) If the interactionId matches an InteractRequest but it has timed out then a TIMEDOUT error shall be returned.
h) The operation shall create new InteractResult and InteractAckResult (resp. InteractConfirm/InteractChoice/InteractValue Result) COM objects to represent the interaction response.
i) The created objects should be stored in the COM archive by the service provider.
j) An InteractComplete COM event shall be created and distributed by the service provider.

Considering the "consumer side", it seems that in case of a time out, the provider creates InteractResult and InteractTimedoutResult COM objects, stores them in the archive and distributes an InteractComplete COM event . A TIMEDOUT error is also returned to the consumer

Considering the "response side", it seems that in case of a time out, the operation creates InteractResult and InteractAck/InteractConfirm/InteractChoice/InteractValue Result COM objects , the provider stores the created objects and distributes an InteractComplete COM event .  A TIMEDOUT error is also returned to the display application

1) Why is the behaviour of the operations and of the provider not symetrical on each side ? Why is it said on the consumer side that an InteractTimedoutResult COM object is created, whereas an  InteractAck/InteractConfirm/InteractChoice/InteractValue  Result COM object is created on the "response" side ?

2) Could you please add a sequence diagram to clarify the behaviour of the interact service in case of time out ?

**Comment by SamCooper** [comment]
On the "response" side, clauses h, i, & j do not apply if the interaction has timed out. the g clause states that a TIMED_OUT error is being returned to the "response" side basically saying "You can't respond to this interaction because it has already timed out".

**Comment by BEHAL** [comment]
OK but to make it clear for everybody, do you not think that it could be worth adding in the "response" operations requirements that clauses h, i, & j do not apply if the interaction has timed out ?

**Comment by SamCooper** [comment]
Done.
