### ISSUE TITLE
COMMON Interact : Cancel interaction

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#21]
For each Interaction Request operation, on the "consumer side", it is said in sections 3.4.7.2, 3.4.9.2, 3.4.11.2 & 3.4.13.2 : 
p) If this operation is cancelled, then a CANCELLED error shall be returned.

On the "response" side it is said in sections 3.4.8.2, 3.4.10.2, 3.4.12.2 & 3.4.14.2 :
f) If the interactionId matches an InteractRequest but it has been cancelled with the cancelInteraction operation then a CANCELLED error shall be returned.
h) The operation shall create new InteractResult and InteractAckResult (resp. InteractConfirm/InteractChoice/InteractValue Result) COM objects to represent the interaction response.
i) The created objects should be stored in the COM archive by the service provider.
j) An InteractComplete COM event shall be created and distributed by the service provider.

The section 3.4.16.2 describing the CancelInteraction operation states :
f) The operation shall create new InteractResult and InteractCancelResult COM objects to represent the interaction response.
g) The created objects should be stored in the COM archive by the service provider.
h) An InteractComplete COM event shall be created and distributed by the service provider.

Considering the "consumer side", it seems that in case of a cancelled interaction, a Cancelled error is  returned to the consumer

Considering the "response side", it seems that in case of a  cancelled interaction, the operation creates InteractResult and InteractAck/InteractConfirm/InteractChoice/InteractValue Result COM objects , the provider stores the created objects and distributes an InteractComplete COM event .  A Cancelled error is also returned to the display application 

Considering the cancelInteraction operation, in this case, the operation creates InteractResult and InteractCancelResult COM objects, the provider stores theses objects in the archive and distributes an InteractComplete COM event

1) Why is the response side generating an InteractAck/InteractConfirm/InteractChoice/InteractValue Result COM object whereas the calcelInteract operation is generating an InteractCancelResult COM object ? 

2) What are the values of the interactAck/InteractConfirm/InteractChoice/InteractValue Result COM object  in this case ?

3) Could you please add a sequence diagram to clarify the behaviour of the interact service in case of a cancelled interaction ?

**Comment by SamCooper** [comment]
1) It is not, that operation will have returned with a CANCELLED error at clause 'f'.
2) See above.

**Comment by BEHAL** [comment]
OK, but to make it clear for everybody do you not think that it could be worth adding in the response operations requirements that clauses h) i) j) do not apply if the inyteraction has been CANCELLED ?

**Comment by SamCooper** [comment]
Done
