### ISSUE TITLE
COMMON : Conditions of use of the UpdateReplay Operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#22]
1) Can the UpdateReplay operation be used no matter the state of the Replay session ? 

2) if it can be used when the replay session is not stopped, when are the modifications taken into account ? Immediately or once the session has been stopped and restarted ?

**Comment by SamCooper** [comment]
1) Yes
2) immediately

operation updated to clarify.
