### ISSUE TITLE
COMMON : Modifications introduced by the UpdateReplay Operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#25]
Requirement j of section 3.5.12.2 states :
j) If the current time or the replay state of the matched replay is modified by this operation call then a new ReplayStatus event shall be published

The playbackSettings data structure only holds 2 fields : the rate and the step interval. Therefore, how can the UpdateReplay operation modify the replay state ?

**Comment by SamCooper** [comment]
The third field of the operation is the new current time.

**Comment by BEHAL** [comment]
I am not sure that I understand how this operation works: the replaystate is either set to STOPPED, FORWARDS or BACKWARDS. The updatereplay operation can either provide a new rate, a new step interval or a new current time. 
Do you mean that if the replaystate of the replay session was set to STOPPED, providing these inputs would modify it to FORWARD or BACKWARD, depending on the value of the new "current time" compared to the previous one ?

**Comment by SamCooper** [comment]
Ah, sorry, I missed the "or the replay state" in the j) requirement.

That should be removed as this operation does not modify the replay state!
