### ISSUE TITLE
COMMON : Source link of a replay object

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#26]
It is said in section 3.5.4 :
a)      The source link of the Replay object should be the object that caused it to be created, most likely a COM OperationActivity object or an operator login in the case of off-line editors being used .

Can you clarify what you mean by "off-line editors" ? Do you consider that an editor can initiate a  replay session ?

**Comment by SamCooper** [comment]
Cut & paste error, removed.
