### ISSUE TITLE
Configuration service : source link of the ConfigurationSwitch event

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#29]
Requirement 3.4.4 d) says that: 
- "The ConfigurationSwitch COM event source link should indicate the object that caused it to be created, most likely a COM OperationActivity object or an operator login in the case of off-line editors being used."

However the only operation that triggers this event seems to be the activate operation and I fail to see how an off-line editor can be used to trigger this event. 
Therefore, should it not be more acurate to say :
 - "The ConfigurationSwitch COM event source link **shall** indicate the  activate OperationActivity object" that caused it to be crated" ?

Please consider clarifying requirement d)

**Comment by SamCooper** [comment]
Done
