### ISSUE TITLE
Configuration service : Scope of Activate operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#31]
Section 3.4.7.1 states that the activate operation instructs **a service provider** to make a specific configuration active, which seems to imply that a composite configuration adressing several providers cannot be activated using this operation.

If my understanding is correct, what is the operation to be used to activate a composite configuration ?

On the contrary, if the activate operation is the one to be used for composite configurations, as the transaction that will be generated by this operation will only be adressed to a specific provider (there is only one destination address in the message header), how will the other providers be informed that they are requested to reconfigure some services ? 

Please complete and clarify

**Comment by SamCooper** [comment]
I am removing Composite configurations from this version as they are of a limited use and make the configuration service too complex for most situations.
They may be reintroduced in a later revision.
