### ISSUE TITLE
Configuration service : ConfigurationSwitched event

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#32]
Requirement 3.4.4 f) says that:
•"f) The ConfigurationSwitched COM event body shall hold the Result of the activation attempt."

The interpretation of the resut is missing. 
Even if it can be considered straightforward, please complete the meaning of the result :  T meaning that the new configuration has been successfully activated

**Comment by SamCooper** [comment]
Updated.
