### ISSUE TITLE
Configuration service : service behaviour in case of partial failure of the activate operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#33]
Statement 3.4.7.2 f)  states that :
f) The service provider that implements the selected service shall, after the reception of the event, reconfigure itself and publish a ConfigurationSwitchResult COM event.

If the configuration activation required is a provider configuration, the activation can succeed for most of the services but fail for only a few of them. 
In this case, what happens to the services whose new configuration has been successfully activated ?  Is there a roll back ?
Please clarify this case.

**Comment by SamCooper** [comment]
The provider must roll back.
Text of operation has been updated.
