### ISSUE TITLE
Configuration service : list operation rules and behaviour

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#35]
I do not understand how this operation is ruled. 

Why the configuration type is one of the inputs and at the same time, requirements c to e of section 3.4.8.2 specify rules to determine the type of configuration ?

What happens if the configuration type selected is "PROVIDER" and none of the service argument fields contains a wild card ?

Furthermore, why should the domain contain a wild card in any of its parts if the selected configuration type is "COMPOSITE" ? I would think that in that case, the operation would return the object instance identifier of all the existing composite configuration objects addressing the selected domain and including the selected service if any.
Please clarify the rules to set up the list operation, its behaviour and consider simplifying the operation to avoid inconsistent inputs.

**Comment by SamCooper** [comment]
I am removing Composite configurations from this version as they are of a limited use and make the configuration service too complex for most situations.
They may be reintroduced in a later revision.
