### ISSUE TITLE
Configuration service : CompositeConfiguration object structure

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#36]
I understand that the CompositeConfiguration objet is a set of ProviderConfiguration objects. However the ProviderConfiguration object does not hold the identifier of the provider it relates to. Therefore, once a CompositeConfiguration object is retrieved from the archive, how can the providers whose configuration is included in this CompositeConfiguration object be identified ?
Please complete and clarify.

**Comment by SamCooper** [comment]
I am removing Composite configurations from this version as they are of a limited use and make the configuration service too complex for most situations.
They may be reintroduced in a later revision.
