### ISSUE TITLE
Configuration service : ProviderConfigurations object

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#37]
Besides the ProviderConfiguration object, table 7 of section 3.4.3 shows an object named ProviderConfigurations which seems to be the source of all the configurations for a specific Provider. However, in the current version of the common services, there is no operation that creates or uses this object.  
How is this object generated ?
Please clarify and complete.

**Comment by SamCooper** [comment]
It is generated during the active operation to show which configuration is currently active for a specific provider.

I have updated the active operation to show this.
