### ISSUE TITLE
Configuration service : List of compositeConfigurations

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#38]
If for instance, the arguments of the list operation are set as follows :
-  area :  4 (MC) 
-  service : 2 (Parameter)
-  Version : 0
-  domain : CNES.PLEIADES
-  type : COMPOSITE
what will the operation return ? All the versions of all the composite configurations in the SPOT domain that include the parameter service  ?
How can the provider receiving this request return the appropriate result ?  Via the archive ?

Please clarify.

**Comment by SamCooper** [comment]
This operation has been updated to clarify the arguments and explain how to use it
