### ISSUE TITLE
Configuration service : inconsistensies or missing specification in the getCurrent operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#39]
1. Requirement 3.4.9.2 a) says : "The domain request argument shall contain the COM object instance identifier" 
I do not think that the domain includes any object instance identifier and there is no such argument in the inputs of the operation
2. Requirements 3.4.9.2 b) and c) define rules when the domain or any of the argument fields contains a wildcard whereas requirement 3.4.9.2 g) says that " No wildcards are supported, an error must be returned in this case", which seems contradictory
3. There is no requirement explaining what result the operation returns

**Comment by SamCooper** [comment]
Updated.
