### ISSUE TITLE
Configuration service : getCurrent operation behaviour

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#40]
Please clarify the behaviour of the getCurrent operation in the following cases :
1) if the service arguments and the domain contain no wildcards and the type argument is set to COMPOSITE or PROVIDER. Is the type ignored, are all service configurations of all the providers matching the criteria returned or is an INVALID error returned ?
2) if the service arguments and the domain contain wildcards and the type argument is set to SERVICE. Are the service configurations returned limited to the services of the  provider of the operation that match the criteria or do the service configurations returned by the operation include all the service configuration of all the providers that match the criteria ?

**Comment by SamCooper** [comment]
Composite configurations have been removed and the operation clarified.
