### ISSUE TITLE
Configuration service : addOperation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#41]
The first argument of the add operation is the object identifier of the configurable object to add the configuration to. 
What are the configurable objects ? There exists a serviceProvider object that is created and used by the directory service, but what is the object defining a service ? The configuration service defines service configuration objects but no "geberic" service object.
 What "configurable" object should be used for a composite configuration  ?

Please clarify and complete the operation specifications.

**Comment by SamCooper** [comment]
UPdated
