### ISSUE TITLE
Configuration service : missing information in the storeCurrent service specification.

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#42]
The input arguments of the storeCurrent operation are the service, the type and a boolean named autoAdd.

1) the function of the autoAdd argument and the way it should be used are not described

2) How should the service arguments be filled when the configuration Type is PROVIDER or COMPOSITE ?

3) In the case of a COMPOSITE configuration type, what is the real scope of the operation ? Does it store in the archive all the configurations of all the providers defined in the directory and matching the specified domain ? 

Please clarify and complete the specifications

**Comment by SamCooper** [comment]
Done
