### ISSUE TITLE
Configuration service : importXML operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#44]
The input argument of this operation is a MAL xmlFile. A MAL file is in particular defined by metadata and a mime Type. 
Should these attributes and the structure of the file not be defined in order to guarantee interoperability ?

Please clarify.

**Comment by SamCooper** [comment]
No, the MIME type would just have XML file. But the file should conform to the correct XML format so that is needed.

I will update the document to show this.
