### ISSUE TITLE
Directory service : withdrawProvider

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#48]
1. Can a provider withdraw itself from the service directory ?

2. Requirement 3.2.9.1 f) says that :
      f)  The service provider should delete the matched object from the COM archive

-  What is the object mentionned in this requirement that should be deleted ? The serviceProvider object ? 
-  What  about the ProviderCapabilities objects, the ConfigurationObjects objects and the ProviderConfiguration objects that are related to the serviceProvider ?
- Same question for the serviceConfiguration objects and the configurationFile objects of the services provided by the withdrawn serviceProvider ?

Please clarify and explain the rationale for deleting this(these) object(s) in the archive

**Comment by SamCooper** [comment]
1) Yes

I have removed the delete aspects from the operation as it not correct.
