### ISSUE TITLE
Directory service : XML files

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#49]
1) Can you confirm that the XML files returned by the getServiceXML operation are the XML ServiceConfiguration files ?  Does it also include the XML ProviderConfiguration files related to the selected provider ? 

2) If that is the case,  how can a consumer identify what XML file corresponds to what serviceConfiguration or ProviderConfiguration object ? 

3) Could the results returned by the operation be completed with at least the object instance identifier of the ServiceConfiguration /  ProviderConfiguration object that it corresponds to ?

4) What about the CompositeConfiguration XML files ?  Can they be found in the service Directory ?

Please clarify and complete the operation specifications

**Comment by SamCooper** [comment]
No, the XML service files returned by the directory service are the service specification XML files. So for instance the XML that we define that specifies the operations of the M&C services for example. 

1) This allows consumers to be aware of any custom services that a provider may be implementing.

2) To get the configuration XML you need to use the configuration service.

I will clarify in the directory service what the XML it returns is.
I will ensure that the configuration service answers the other Q's above.

**Comment by SamCooper** [comment]
Done for configuration service
