### ISSUE TITLE
Login service : generalities

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#50]
Section 3.3.1 says :
" It is expected that the login roles are maintained by the users responsible for the login service provider."

Can you clarify this sentence ? Do you mean that the login roles should be maintained by a dedicated group of users ? 
Why the ones responsible for the login service provider ? 
The list of possible roles is usually defined from an organisational and operational standpoint.

**Comment by SamCooper** [comment]
I have updated it to "The responsibility for maintenance of the login roles is outside the scope of this specification as it is a deployment issue to define the possible roles and associate users to those roles."
