### ISSUE TITLE
Login service : Archive service usage

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#51]
Section 3.3.6 d) says :
d) The COM archive operations shall be used for creating/updating/deleting the LoginRole objects

Please consider completing this requirement by naming the operations. For instance :
d) The COM archive operations, **respectively store/update/delete**, shall be used for creating/updating/deleting the LoginRole objects

**Comment by SamCooper** [comment]
I have updated it to: "The COM archive service shall be used for maintaining the LoginRole objects."
