### ISSUE TITLE
Configuration service : add operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#52]
The add operation of the configuration service is said to make a new configuration available on the configuration service.
 Does it also update the service Directory by completing the list of XML files associated with the provider ? 

Or is it the reverse, i.e the provider has firstly to update the service Directory before adding the new configuration to the Configuration Service ?

Please clarify.

**Comment by SamCooper** [comment]
There is no relationship between the XML held in the directory service and the configuration service configurations.
