### ISSUE TITLE
Configuration service : ServiceProviderKey

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#53]
The comment attached to the domain field of the ServiceProviderKey says that "The domain field supports the wildcard value of "*" only in the last part of the domain whereas :

-  Requirements 3.4.8.2 c) & 3.4.9.2 b) say : "if the domain contains a wild card in any of its part ..." 

Please clarify aand harmonize.

**Comment by SamCooper** [comment]
I have removed the type and moved the wildcard requirements into the relevant operations.
