### ISSUE TITLE
All COM Archive-related requirements must be "should"

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/COMMON_SPEC_RIDS#54]
Line 467:  
<com:archiveUsage comment="LoginInstance objects shall be stored in the COM archive.&#xA;When a login service event is published, the event object shall be stored in the COM archive by the Login service provider.&#xA;LoginRole objects shall be stored in the COM archive.&#xA;The COM archive service shall be used for maintaining the LoginRole objects."/> 

All COM Archive-related requirements must be "should" requirements.
This is a must because the services cannot have hard links to other services.
The idea behind is that any MO service can be implemented without having to rely on any other services.

**Comment by SamCooper** [comment]
Done
