### ISSUE TITLE
Improvement suggestion on COM Objects and COM Events

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/COMMON_SPEC_RIDS#55]
There are two separate suggestions.

1. Change the alignment of the representation on the COM Objects and COM Events.
Example:
From:
A ServiceProvider object represents a service provider. The COM object body shall hold the service provider name.
The ServiceProvider COM object related link shall not be used and therefore set to NULL.
The ServiceProvider COM object source link shall not be used and therefore set to NULL.
A ProviderCapabilities object represents the supported capabilities of a service provider. The COM object body shall hold the provider details of the service provider.
The ProviderCapabilities COM object related link shall indicate which ServiceProvider COM object it links to.
The ProviderCapabilities COM object source link shall not be used and therefore set to NULL.
ServiceProvider and ProviderCapabilities objects shall be created by the publishService operation.
The object instance identifier for the ServiceProvider and ProviderCapabilities objects shall be populated by the provider of the directory service.
For the AddressDetails of a particular ProviderCapabilities object, if the brokerProviderObjInstId field contains a value and the brokerURI field is NULL, then the brokerURI value of the referenced provider shall be used.

To:
A ServiceProvider object represents a service provider. The COM object body shall hold the service provider name.
<ol>
<li>The ServiceProvider COM object related link shall not be used and therefore set to NULL.</li>
<li>The ServiceProvider COM object source link shall not be used and therefore set to NULL.</li>
</ol>
A ProviderCapabilities object represents the supported capabilities of a service provider. The COM object body shall hold the provider details of the service provider.
<ol>
<li>The ProviderCapabilities COM object related link shall indicate which ServiceProvider COM object it links to.</li>
<li>The ProviderCapabilities COM object related link shall indicate which ServiceProvider COM object it links to.</li>
<li>The ProviderCapabilities COM object source link shall not be used and therefore set to NULL.
ServiceProvider and ProviderCapabilities objects shall be created by the publishService operation.</li>
</ol>
....

2. One can follow the guidelines presented here:
https://docs.google.com/document/d/1pDTS2Ff8X8Cjb0DnzXFYjRU2DDtHRxXOifT2JOQQNZA/edit

The services are almost all aligned with it already. Most likely, it won't take much effort to complete it.

**Comment by SamCooper** [comment]
I agree with your formatting suggestion but it is not within CCSDS document guidelines therefore we won't get it past Tom.
