### ISSUE TITLE
Configuration service : service start-up

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#56]
Section 2.7.3  says : 
3. Call getCurrent to retrieve the **current configuration** of the provider according to the Configuration service.
4. Activate the **“current”** configuration

This example implies that the getCurrent operation returns the identifier of a service configuration that has not been activated. 
If this case, how can the getCurrent operation determine what is the "current" configuration of a service in the list of the available service configurations of the configuration service ?
I do not see any operation of the configuration service that "flags" one of the available configurations as the "current one", the add operation merely making a new configuration available on the configuration service but not declaring it as the "current" one.

Can you please clarify and complete this section if needed ?

**Comment by SamCooper** [comment]
I've clarified that getCurrent returns "last activated" but also added in text that indicates that implementations of the configuration service may have their own ways of triggering an activation outside of the activate operation (this is to cover cases where a configuration change happens but the active operation is not explicitly called).

I've then updated 2.7.3 to cover this and changed 2.7.3.4 to make clear that active is not being called but the configuration returned from getCurrent is just used by the service being started to configure itself.
