### ISSUE TITLE
Configuration service : origin of the configuration objects used by the configuration service operations

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#57]
For some of the operations of the configuration service, it is not said if they only work with  the configurations available in the configuration service or if they can also work with the configuration objects stored in the COM archive. Can you clarify what type of configurations are used by the following operations :
-  Activate 
-  list
Is it a general principle of the configuration service that a configuration must firstly be added in the configuration service before being listed, activated or removed ?

If these operatiosn can work with the archive, what is the purpose in this case of the add operation ?

Please clarify and complete either the operations concerned or the general section.

**Comment by SamCooper** [comment]
I have clarified the operations that they must have been "added" first.
