### ISSUE TITLE
Configuration service : scope of the add operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#58]
Requirement 3.4.11.2 b) states that :
b) The second argument shall contain a list of **provider configurations** to add to the list of configurations available for the specific service provider
This 1st statement seems to imply that **only provider configurations** can be made available on the configuration service and that it is not possible to add a service configuration, although the structure of the operation does not prevent it.

However, the storeCurrent operation indicate that:
"The storeCurrent generates a new Configuration object with the current Configuration of **a specific Service or Provider configur**ation and stores it in the COM archive. Optionally the **configuration can be added to the list of available configurations**"
This 2nd  statement seems to imply on the contrary that it is possible to add a service configuration to the list of available configurations.

Please clarify and harmonize.

**Comment by SamCooper** [comment]
I have changed the add operation to be clear that service configurations can be added too.
