### ISSUE TITLE
Configuration service : scope of the storeCurrent operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#59]
The general section of the storeCurrent operation indicates that "the storeCurrent generates a new Configuration object with the current Configuration **of a specific Service or Provider configuration** and stores it in the COM archive." 
Requirement 3.4.13.2 d) also says that "The service provider that implements **the selected service** shall, after the reception of the event, store the current Configuration in the COM Archive"

However, if the requested configuration to store is a service configuration, the storeCurrent operation has no input argument to specify the service whose configuration should be stored and optionally added to the list of available configuration.
How is this information passed on  to the service provider ?
Please clarify and complete.

**Comment by SamCooper** [comment]
I've added a field to the operation for specifying the service and also added it to the event published.
