### ISSUE TITLE
Configuration service : COM archive service usage

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#60]
It is said in §3.4.6 that :
a) Configuration definition objects **should** be stored in the COM archive. 
b) The COM objects that hold the actual configuration definition details **should** be stored in the COM archive

However, if I hypothesize that only configurations available in the configuration service can be activated or listed, it implies that at one point, these configurations have been made available on the configuration service.
The operations that can add a configuration to the list of available configurations are the "add" operation and the "storeCurrent" operation. Both operations impose that the added configuration be in the archive before it is added.

Therefore, if I am right, it is mandatory to store the service and the provider configuration objects in the archive. 

Can you clarify ?

**Comment by CesarCoelho** [comment]
Hi Brigitte,
I believe that all "COM Archive" requirements must be "should".
Check here for the explanation: https://github.com/SamCooper/COMMON_SPEC_RIDS/issues/54

**Comment by SamCooper** [comment]
yes, you could build an implementation of the login service without a COM archive as it is backed (for example) by an existing security system.

So dependence on the COM archive is _should_ rather than _shall_
