### ISSUE TITLE
Configuration service : getCurrent operation arguments

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#63]
The table in § 3.4.9.1 indicate that the 1st  input field of the getCurrent operation is "**List**<COM::ObjectKey>. 
However the description in § 3.4.9.1 and requirement 3.4.9.2 a) both stipulate that the getCurrent operation only queries a service provider and not a list of service providers.

Please clarify and harmonize.

**Comment by SamCooper** [comment]
That should not be a List, I have fixed that.
