### ISSUE TITLE
Configuration service : scope of the importXML operation

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#64]
Section 3.4.14.1 says that "Afterwards, the configuration can be optionally added to the list of available configurations".
However, there is no option in the importXML arguments that enables to add the configuration to the list of available configurations.

Is this "addition" outside the scope of the importXML operation and supposed to be performed using the add operation ? 

Please clarify and complete if needed.

**Comment by SamCooper** [comment]
I've changed the text to be "Afterwards, the configuration can be added to the list of available configurations using the add operation."
