### ISSUE TITLE
Configuration service: 2.7 CONFIGURATION SERVICE USE CASES

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/COMMON_SPEC_RIDS#69]
Section 2.7.3 seems like an implementation detail.
I would suggest to completely remove section 2.7.3 as it seems to be simultaneously outdated and an implementation detail.

If not possible, please add a note on section 2.7.3 to clarify that a provider does not necessary need to start-up as suggested there.

**Comment by SamCooper** [comment]
Done.
