### ISSUE TITLE
COMMON Login service  : source of the login and logout Events

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#7]
Requirement f) of section 3.3.5 states :
f) The events shall not use the COM object source link and shall set it to NULL.

Whereas table 3-5 indicates "not specified" in the column "source points to" .

It should be more straightforward to indicate "NULL" in this column to make the difference with the cases where there is really a source object that is not specified.

**Comment by SamCooper** [comment]
Done
