### ISSUE TITLE
Directory service: Add uriSchemeName field on ServiceFilter

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/COMMON_SPEC_RIDS#70]
In case a certain provider is using multiple transports, we might want to filter for a specific one.

Use case example:
I have 1 Parameter service exposed via RMI and via SPP on my s/c. The rmi would be used only for ipc.
When I do my lookup from ground, I will never use the rmi transport (because I don't have access to that connection) and instead, I can only use spp.
So, what I would like to do is to filter for a certain transport and avoid getting URIs for other transports that cannot even be used for the space-to-ground link.

So:
Field: uriSchemeName
Type: MAL::URI
Nullable: Yes
Comment: The URI scheme name to match, for example 'malspp'. Can be NULL in which case matches all values.

Please also add on the lookup operation the missing requirements for the matching of the URI scheme name.

**Comment by SamCooper** [comment]
I don't think this is a good idea as discussed by email. It is an extra complication for a limited use case that can be handled quite simply in the consumer.
