### ISSUE TITLE
[Directory Service] Use of the Archive

### ISSUE THREAD

**Issue by ochurlaud** [SamCooper/COMMON_SPEC_RIDS#79]
What is the objective of storing the state of the Directory service in the Archive service. The use of those store objects is not explicit in the specification. They are only written, not read.

Are there any expected direct accesses to the Archive data, by the Directory service itself or by other services ? In that case a possible discrepancy between the service state and the stored image could be a problem. Discrepancies could result from an error during an Archive interaction, or from the fact that WithdrawProvider has no impact on Archive.

**Comment by SamCooper** [comment]
It is not intended to be used to store current state, but to store history, i.e. work out what happened and when.

Is there a change to the specification required here?

**Comment by lacourte** [comment]
With this expected usage in mind, I dont think a change is really needed.

**Comment by SamCooper** [comment]
Ok, I'll close this then
