### ISSUE TITLE
COMMON Login service  : management of LoginRole objects 

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#8]
I do not understand how the loginRole objects are managed : 
it is said in requirement c) of section 3.3.7 that "loginRole objects shall be stored in the archive" but I do not find any operation creating loginRole objects. When and by whom are the loginRole objects created ?

it is also said in Requirement d) of section 3.3.7  "The login service shall use the COM archive operations for maintaining the login roles" . Does this sentence refer to the loginRole objects ? 

Can you clarify what "maintening the login roles" means ?

**Comment by SamCooper** [comment]
Done.
