### ISSUE TITLE
[Configuration Service] Use of the directory service

### ISSUE THREAD

**Issue by ochurlaud** [SamCooper/COMMON_SPEC_RIDS#80]
The use of the directory service is not explicit in the specification. There is notably no such section as sections 3.4.4 and 3.4.6 which describe the use of the services Event and Archive.

However a service provider is identified in the API as a ServiceProvider COM object, which probably makes it mandatory for the service provider to register in the Directory service in order to be managed by the Configuration service.

This conflicts with another preliminary assertion in section 2.5:

> It should be noted that the[re] is no direct relationship between the contents of the Directory service and the Configuration service. For example, there can be a different set of providers in an instance of the Directory service to that managed by an instance of the Configuration service. Basically, the Directory service is used to hold the address and the supported operations of providers whereas the Configuration service is used to hold the configuration of providers, however there is no requirement for these two sets of providers to be the same (although that may make sense in some deployments).

**Comment by SamCooper** [comment]
So, basically if there is no Directory Service how do I get my ServiceProvider COM objects?

**Comment by lacourte** [comment]
For the tests I allocate my own id and stores the ServiceProvider object in Archive. This would probably work in a real environment, as long as you let Archive allocate the id to avoid collisions.

**Comment by SamCooper** [comment]
Ok, so I can put in a comment indicating how it works when you don't have a directory service.

Would that be ok?

**Comment by lacourte** [comment]
Yes I think so

**Comment by SamCooper** [comment]
I have stated that the MO way of doing this is to use the Directory service to create them (i.e. they are shared), but that it is not a requirement. However if you do not link them then the mechanism for creating them is implementation specific.

I think for the tests it is probably best to either require them to already exist as part of the test scenario or add operation to a test service to create them.
