### ISSUE TITLE
Current configuration

### ISSUE THREAD

**Issue by lacourte** [SamCooper/COMMON_SPEC_RIDS#85]
The concept of a currently active or currently selected configuration is used throughout the specification of the Configuration service, but it looks ambiguous sometimes.
I would like to add an overall comment in section 3.4.1 which would state:
If a service provider chooses to be managed by the Configuration service, then its currently active configuration shall be defined by a call to the operations storeCurrent or activate.

**Comment by SamCooper** [comment]
Does this imply that you cannot change the configuration of that service provider by any other means?

**Comment by lacourte** [comment]
Yes and no. It is a matter of what you understand by configuration.
The modification I propose fixes the signification of "currently active configuration". It allows the Configuration service to answer to a call to the getCurrent operation.
The service provider may change its configuration by any other means, however in that case the Configuration service would not know of that change and will answer a call to getCurrent by providing the former one.
As I said, this term of "currently active configuration" is ambiguous. I want to remove this ambiguity by precising what is the "currently active configuration". I do not force the actual configuration of the component to be that configuration.
Another way of removing the ambiguity would be to force the "currently active configuration" of the provider to be the actual configuration of the provider. However I do not find it possible as the standard is written.

**Comment by SamCooper** [comment]
Ok, so it is a definition of what the configuration service specification means by "currently active configuration" and that is "What the Configuration Service implementation thinks it is" rather than "What the specific service provider X knows it is". Correct?

**Comment by lacourte** [comment]
Exactly.

**Comment by SamCooper** [comment]
Ok, I have added a comment to the getCurrent operation to explain this.
