### ISSUE TITLE
[Directory Service] Spec states session type can be empty but is restricted to an enum

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#86]
The spec states : 

> b) If any of the fields of the newProviderDetails domain/sessionType/SessionName/network fields are either empty or contain the wildcard '*' an INVALID error shall be returned."

However the sessionType field is an enum on the PublishDetails object which means it can never contain an empty or wildcard value so it's likely the sessionType should be removed from that requirement.

**Comment by SamCooper** [comment]
Done
