### ISSUE TITLE
[Directory Service] Ambiguity over fields on the PublishDetails object

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#87]
The spec states: 

> d) If the area/service/version fields of the PublishDetails structure contain '0' or the supportedCapabilitySets list is empty or contains '0' then an INVALID error shall be returned."

This suggests that the PublishDetails structure contains an area, service and version field which they do however these are the auto-generated constants for the particular type which are unchanging.

For the prototype I've assumed the area, service and version fields referenced here are referring to the fields of the service key of each of the service capabilities that it provides (PublishDetails->ProviderDetails->ServiceCapabilitiesList->ServiceCapability->ServiceKey) and the validation is applied to each. 

The same applies to the supported capability sets.

The above solution may not be correct so it's worth clarifying that in the spec.

**Comment by SamCooper** [comment]
Yep, you are correct. I've updated/split the requirement to clarify:

For each contained ServiceKey structure if the area/service/version fields contain '0' then an INVALID error shall be returned.
For each contained supportedCapabilitySets list if the list is empty or contains '0' then an INVALID error shall be returned.
