### ISSUE TITLE
[Directory Service] Clarity regarding wildcarded domains

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#88]
This may be somewhat subjective but I just wanted clarity on the following statement from the spec:

> If the final identifier of the domain field of the filter is the wildcard '*', then all sub-domains shall be searched for matches."

Is this suggesting that given a list of domains to filter on if the list is :

[a,b,c,*]

Then return everything. This seems a bit odd as it effectively ignores the a,b,c entries and is equivalent to:

[*]

Or is it suggesting that we can include wildcards in the domain e.g

[a*,b*,c*]

Which would match domains beginning with a or b or c

**Comment by SamCooper** [comment]
No, a domain is built up like a URL, so [a, b, c, *] is actually "a.b.c.*", so matches "a.b.c" and "a.b.c.d" but not "a" or "a.b".

There is a good explanation of this is the MAL specification I think, I shall link to that
