### ISSUE TITLE
[Directory Service] Does the filter apply a logical AND or a logical OR?

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#89]
In a normal filter functionality I'd expect it to filter based on a logical ORing of the individual filter attributes but this is not specified in the spec. I'm going to assume it's a logical OR of the different filter attributes and not an AND for the prototype.

E.g if we pass a provider Id of 1 and a network of 'network' does an entry match when the provider ID is 1 AND has a network ID of 'network' or is it when the entry has an ID of 1 OR it has a network ID of 'network'?

**Comment by apinder** [comment]
Update: I've managed to find that it's a logical AND so this is less of a concern and can likely be closed my only concern is that it's in chapter 4 (data types) whereas I'd expect it to be part of the service directory specification (chapter 3.2) as it's closer to directory service functionality than it is type information but this is more of a minor issue now.

**Comment by SamCooper** [comment]
I've added a small note to the summary of this operation to make it clear.
