### ISSUE TITLE
COMMON Login service  : flowchart of the service

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/COMMON_SPEC_RIDS#9]
The sequence of operations of the  login service is not obvious to me.  Is the following sequence correct ?
1) the user activates the login service 
2) the application in charge of managing the login  uses the reportRoles operation to check the login validity
3) the provider creates the loginInstance object, links it to the corresponding loginRole object
4) the provider stores the loginInstance object  in the archive

A flowchart of the sequence of operations would be useful. 
Please consider adding it.

**Comment by SamCooper** [comment]
There are sequence diagrams in the reference model for this, I have added the following text:

The Reference Model (R2) also provides sequence diagrams for security and login in sections 5.2 and 5.3.
