### ISSUE TITLE
[Directory Service] Clarity on the service key match

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#90]
At the moment it's not too clear that the service key specified in the filter refers to the service keys of the service capabilities of the provider and that the filter should be applied to all of the service capabilities, assuming this interpretation is correct.

The only relevant requirement I can find from the spec is the negative case : 

> i) If the serviceKey field is NULL then all areas, services and versions shall be matched."

**Comment by SamCooper** [comment]
I have added extra text to hopefully clarify this.
