### ISSUE TITLE
[Directory Service] LookupProvider multiple domain IDs filter match unspecified

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#91]
Spec mentions:

> "e) If the domain field is NULL then all domains shall be matched." 

This is the negative case but what about the positive case?

In this case if a domain ID is passed in the filter and that domain ID is contained in any of the existing published providers is that a positive match or is it only a match if all domain ids passed in the filter match the appropriate provider? E.g is this an ANDing or is this an ORing of the domain IDs when we apply the lookup filter?

**Comment by SamCooper** [comment]
This is a confusion of how we build domain Ids. The list is not a list of domains but a list of domain parts, so a domain (which is very similar to URL) of "org.ccsds.moims.mo" would be held as ["org", "ccsds", "moims", "mo"]
