### ISSUE TITLE
[Login service] Clarity need on the 'Permitted maximum usage value'

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#94]
> 3.3.7.2 g) A TOO_MANY error shall be returned if the username or role are already used and exceed the permitted maximum usage value (deployment dependent).

For us to know the 'permitted maximum usage' we need to know implementation details of the deployment. One way to do this would be to provide the login service with an interface that allows callees to notify the service to specify what the permitted maximum usage value is. It's also not entirely clear what the 'permitted maximum usage' value represents.

**Comment by SamCooper** [comment]
In some systems you may be able to log in more than once, or have many people using the same role, however in others only one person may be allowed in certain roles.

I will clarify what is meant by this.

**Comment by SamCooper** [comment]
Updated to:
A TOO_MANY error shall be returned if the username or role are already used and exceed (deployment dependent) maximum number of concurrent logins/roles.
