### ISSUE TITLE
[Login service] How do we make the Login service aware of existing users

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#95]
At the moment we have no mechanism within the current login service to add/remove users. For the purposes of the prototype I've created a Login Test service that allows us to do this but in a real world scenario the login service needs to be aware of what users it currently has to provide authentication.

**Comment by SamCooper** [comment]
Well an implementation of the login service would be a thin wrapper around an existing security system.

The service is not intended to be a standard for security implementations, but a standard for presenting a common API to client applications.
