### ISSUE TITLE
[Login service] The Logout COM event has its source pointing to its equivalent LoginEvent however it's not clear what this object should be

### ISSUE THREAD

**Issue by apinder** [SamCooper/COMMON_SPEC_RIDS#99]
The requirement in question is:

> 3.3.4 The LogoutEvent event shall use the source link to indicate which LoginEvent event it is logging out

With regard to COM Events there is no explicit event object that we can use to point to. We could use the ObjectDetails passed inside the event but that will contain the LoginInstance ID which is already available as the related part of the event

**Comment by SamCooper** [comment]
A COM Event is an extension to a COM Object.

Does that help?

**Comment by apinder** [comment]
That clarifies what I thought yes, however there's still a problem (or my misunderstanding :) )

So the COM Event to link to is: 

```
        <com:event name="LoginEvent" number="3">
            <com:relatedObject>
              <com:objectType number="2" service="Login" area="Common"/>
            </com:relatedObject>
          </com:event>
```

The problem is that unlike the `LoginInstance` COM object it doesn't have a `<com:objectType>` so to construct a reference to the login event for the logout event there's no way of creating it programatically. 

Alternatively we could save the login COM Event to the archive and then read it back (if possible) although I'm not sure how that works when there's no `<com:objectType>`.

**Comment by SamCooper** [comment]
Clarified offline
